### PR TITLE
Support for multiple intervals

### PR DESCRIPTION
**Pull request by ralvs**
This way is possible to add the same alert in multiple timeframes of a symbol

### CODE REVIEW

**Comment by arnoudb** [comment]
I was about to ask this as a feature request. Would be awesome if this can be merged!

**Comment by ocmich74** [comment]
How do you add multiple timeframes?  What is the format? I tried 30m, 1h on the config.yml page and it only did 30m.

**Comment by ralvs** [comment]
As follow:

interval: 5m,15m,1h,4h

Without spaces

**Comment by mlake** [comment]
hi there, this feature will be in the 2.0 release coming soon

**Pull request closed without merging**
